#!/bin/bash
set -e

BOOTSTRAPPED="/var/lib/ldap/.bootstrapped"

if [ ! -e $BOOTSTRAPPED ]; then
	get_base_dn() {
		BASE_DN=""
		IFS='.' read -ra BASE_DN_TABLE <<< "$LDAP_DOMAIN"
		for i in "${BASE_DN_TABLE[@]}"; do
			EXT="dc=$i,"
			BASE_DN=$BASE_DN$EXT
		done

		BASE_DN=${BASE_DN::-1}
	}

	is_new_schema() {
		local COUNT=$(ldapsearch -Q -Y EXTERNAL -H ldapi:/// -b cn=schema,cn=config cn | grep -c $1)
		if [ "$COUNT" -eq 0 ]; then
			echo 1
		else
			echo 0
		fi
	}

	## Set configuration
	cat <<-EOF | debconf-set-selections
	slapd slapd/password1 password ${LDAP_ADMIN_PASSWORD}
	slapd slapd/internal/adminpw password ${LDAP_ADMIN_PASSWORD}
	slapd slapd/password2 password ${LDAP_ADMIN_PASSWORD}
	slapd slapd/internal/generated_adminpw password ${LDAP_ADMIN_PASSWORD}
	slapd slapd/move_old_database boolean true
	slapd slapd/allow_ldap_v2 boolean false
	slapd slapd/dump_database select when needed
	slapd slapd/dump_database_destdir string /var/backups/slapd-VERSION
	slapd slapd/no_configuration boolean false
	slapd shared/organization string ${LDAP_ORGANISATION}
	slapd slapd/purge_database boolean false
	slapd slapd/domain string ${LDAP_DOMAIN}
	slapd slapd/backend select MDB
	EOF

	dpkg-reconfigure -f noninteractive slapd

	slapd -h "ldapi:///" -u openldap -g openldap

	ldapmodify -Y EXTERNAL -Q -H ldapi:/// \
		<<-EOF
		dn: olcDatabase={1}mdb,cn=config
		changetype: modify
		delete: olcAccess
		-
		add: olcAccess
		olcAccess: {0}to attrs=userPassword,shadowLastChange by self write by anonymous auth by dn="cn=admin,${BASE_DN}" write by * none
		-
		add: olcAccess
		olcAccess: {1}to dn.base="" by * read
		-
		add: olcAccess
		olcAccess: {2}to * by self write by dn="cn=admin,${BASE_DN}" write by * none
		-
		EOF

	# add ppolicy schema if not already exists
	ADD_PPOLICY=$(is_new_schema ppolicy)
	if [ "$ADD_PPOLICY" -eq 1 ]; then
		ldapadd -c -Y EXTERNAL -Q -H ldapi:/// -f /etc/ldap/schema/ppolicy.ldif
	fi

	pkill -INT -F /run/slapd/slapd.pid

	touch $BOOTSTRAPPED
fi

# Reduce maximum number of number of open file descriptors to 1024
# otherwise slapd consumes two orders of magnitude more of RAM
# see https://github.com/docker/docker/issues/8231
ulimit -n 1024

exec /usr/sbin/slapd -h "ldap:/// ldapi:///" -u openldap -g openldap -d -1 -s syslog-level